### ISSUE TITLE
Fetching latest image in family

### ISSUE THREAD

**Issue by zbjornson** [googleapis/nodejs-gce-images#8]
I haven't debugged this yet (won't have time to for at least a day), but attempting to fetch the latest image in a family from a project seems to fail. Not sure if this is supposed to work, but it would certainly be nice.

```js
client.getAll("my-project/", console.log) // logs all of my private images
client.getAll("my-project/my-family", console.log) // Error: Could not find a suitable image
```

For reference, an image that I would expect the last one to return looks like this:

```js
{
  // ...
  family: "my-family",
  selfLink: "https://www.googleapis.com/compute/v1/projects/my-project/global/images/my-image-1507225306"
  // ...
}
```

**Comment by bcoe** [comment]
We're no longer iterating on this library (just keeping on top of bugs and security issues).

Closing this out, as I don't think we'll every get to this ... I'm also guessing you've moved on 😆
